/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-briefcase' : '&#xe000;',
			'icon-expand' : '&#xe001;',
			'icon-google-plus' : '&#xe002;',
			'icon-html5' : '&#xe003;',
			'icon-monitor' : '&#xe004;',
			'icon-mobile' : '&#xe005;',
			'icon-tablet' : '&#xe006;',
			'icon-bookmarks' : '&#xe007;',
			'icon-bookmark' : '&#xe008;',
			'icon-bookmark-2' : '&#xe009;',
			'icon-facebook' : '&#xe00a;',
			'icon-twitter' : '&#xe00b;',
			'icon-github' : '&#xe00c;',
			'icon-envelope' : '&#xe00d;',
			'icon-locked' : '&#xe00e;',
			'icon-bookmark-3' : '&#xe00f;',
			'icon-list' : '&#xe010;',
			'icon-layers-alt' : '&#xe011;',
			'icon-fullscreen-alt' : '&#xe012;',
			'icon-fullscreen-exit' : '&#xe013;',
			'icon-fullscreen-exit-alt' : '&#xe014;',
			'icon-fullscreen' : '&#xe015;',
			'icon-move' : '&#xe016;',
			'icon-move-alt1' : '&#xe017;',
			'icon-window' : '&#xe018;',
			'icon-camera' : '&#xe019;',
			'icon-code' : '&#xe01a;',
			'icon-phone' : '&#xe01b;',
			'icon-eye' : '&#xe01c;',
			'icon-target' : '&#xe01d;',
			'icon-checkmark' : '&#xe01e;',
			'icon-checkbox-checked' : '&#xe01f;',
			'icon-checkbox-unchecked' : '&#xe020;',
			'icon-checkbox-partial' : '&#xe021;',
			'icon-filter' : '&#xe022;',
			'icon-hammer' : '&#xe023;',
			'icon-wrench' : '&#xe024;',
			'icon-expand-2' : '&#xe025;',
			'icon-contract' : '&#xe026;',
			'icon-lightning' : '&#xe027;',
			'icon-phone-2' : '&#xe028;',
			'icon-phone-hang-up' : '&#xe029;',
			'icon-envelop' : '&#xe02a;',
			'icon-location' : '&#xe02b;',
			'icon-location-2' : '&#xe02c;',
			'icon-map' : '&#xe02d;',
			'icon-map-2' : '&#xe02e;',
			'icon-home' : '&#xe02f;',
			'icon-barcode' : '&#xe030;',
			'icon-qrcode' : '&#xe031;',
			'icon-profile' : '&#xe032;',
			'icon-images' : '&#xe033;',
			'icon-image' : '&#xe034;',
			'icon-camera-2' : '&#xe035;',
			'icon-home-2' : '&#xe036;',
			'icon-stack' : '&#xe037;',
			'icon-folder' : '&#xe038;',
			'icon-cog' : '&#xe039;',
			'icon-cogs' : '&#xe03a;',
			'icon-cog-2' : '&#xe03b;',
			'icon-menu' : '&#xe03c;',
			'icon-menu-2' : '&#xe03d;',
			'icon-arrow-right' : '&#xe03e;',
			'icon-arrow-up-left' : '&#xe03f;',
			'icon-arrow-up' : '&#xe040;',
			'icon-arrow-up-right' : '&#xe041;',
			'icon-arrow-down-right' : '&#xe042;',
			'icon-arrow-down' : '&#xe043;',
			'icon-arrow-down-left' : '&#xe044;',
			'icon-arrow-left' : '&#xe045;',
			'icon-mail' : '&#xe046;',
			'icon-mail-2' : '&#xe047;',
			'icon-mail-3' : '&#xe048;',
			'icon-embed' : '&#xe049;',
			'icon-code-2' : '&#xe04a;',
			'icon-console' : '&#xe04b;',
			'icon-new-tab' : '&#xe04c;',
			'icon-indent-increase' : '&#xe04d;',
			'icon-indent-decrease' : '&#xe04e;',
			'icon-paragraph-justify' : '&#xe04f;',
			'icon-picassa' : '&#xe050;',
			'icon-picassa-2' : '&#xe051;',
			'icon-wrench-2' : '&#xe052;',
			'icon-picture' : '&#xe053;',
			'icon-cog-3' : '&#xe054;',
			'icon-file-pdf' : '&#xe055;',
			'icon-apple' : '&#xe056;',
			'icon-android' : '&#xe057;',
			'icon-compass' : '&#xe058;',
			'icon-print' : '&#xe059;',
			'icon-logo-blanc' : '&#xe05a;',
			'icon-logo-gris' : '&#xe05b;',
			'icon-logo4' : '&#xe05c;',
			'icon-noun_project_8544' : '&#xe05d;',
			'icon-noun_project_8545' : '&#xe05e;',
			'icon-photos' : '&#xe05f;',
			'icon-bookmark-4' : '&#xe060;',
			'icon-ergo' : '&#xe061;',
			'icon-noun_project_1681' : '&#xe062;',
			'icon-noun_project_1280' : '&#xe063;',
			'icon-noun_project_1171' : '&#xe064;',
			'icon-inte' : '&#xe065;',
			'icon-noun_project_19036' : '&#xe066;',
			'icon-home-3' : '&#xe067;',
			'icon-newspaper' : '&#xe068;',
			'icon-unlocked' : '&#xe06a;',
			'icon-leaf' : '&#xe06b;',
			'icon-attachment' : '&#xe06c;',
			'icon-airplane' : '&#xe06d;',
			'icon-quotes-left' : '&#xe069;',
			'icon-quotes-left-2' : '&#xe06e;',
			'icon-ergo-2' : '&#xe06f;',
			'icon-award-stroke' : '&#xe070;',
			'icon-award-fill' : '&#xe071;',
			'icon-arrow-right-alt1' : '&#xe072;',
			'icon-arrow-left-alt1' : '&#xe073;',
			'icon-arrow-right-2' : '&#xe074;',
			'icon-arrow-left-2' : '&#xe075;',
			'icon-eye-2' : '&#xe076;',
			'icon-map-pin-stroke' : '&#xe077;',
			'icon-map-pin-fill' : '&#xe078;',
			'icon-map-pin-alt' : '&#xe079;',
			'icon-star' : '&#xe07a;',
			'icon-unlock-fill' : '&#xe07b;',
			'icon-unlock-stroke' : '&#xe07c;',
			'icon-lock-fill' : '&#xe07d;',
			'icon-lock-stroke' : '&#xe07e;',
			'icon-camera-3' : '&#xe07f;',
			'icon-layers' : '&#xe080;',
			'icon-left-quote' : '&#xe081;',
			'icon-right-quote' : '&#xe082;',
			'icon-left-quote-alt' : '&#xe083;',
			'icon-right-quote-alt' : '&#xe084;',
			'icon-wrench-3' : '&#xe085;',
			'icon-cog-4' : '&#xe086;',
			'icon-mail-4' : '&#xe087;',
			'icon-document-alt-stroke' : '&#xe088;',
			'icon-document-alt-fill' : '&#xe089;',
			'icon-lightbulb' : '&#xe08a;',
			'icon-magnifying-glass' : '&#xe08b;',
			'icon-download' : '&#xe08c;',
			'icon-cloud-download' : '&#xe08d;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};